### PR TITLE
Python: DevUI Fix Serialization, Timestamp and Other Issues

### LINKED ISSUE #1483: Python: DevUI - Tool call timestamps are being overwritten
When multiple tool calls happen, each new call updates the timestamp shown on all previous cards in the DevUI timeline.

As a result, every “Tool Call” and “Tool Result” ends up showing the same (latest) time instead of its actual creation time.

- **Expected:** each tool event keeps its original timestamp.
- **Actual:** all timestamps are overwritten with the latest one.

Image

Image

### LINKED ISSUE #1548: Python: DevUI returns error with AgentOrchestration patterns
When using the DevUI with a `ConcurrentBuilder()` workflow I get an error serializing `ChatMessage`. When this happens the UI goes blank.

```
[2025-10-17 10:26:04 - /mitted/agent-framework-learning/.venv/lib/python3.13/site-packages/agent_framework_devui/_server.py:544 - ERROR] Error in streaming execution: Unable to serialize unknown type: <class 'agent_framework._types.ChatMessage'>
```

Versions:

agent-framework                          1.0.0b251016
agent-framework-a2a                      1.0.0b251016
agent-framework-azure-ai                 1.0.0b251016
agent-framework-copilotstudio            1.0.0b251016
agent-framework-core                     1.0.0b251016
agent-framework-devui                    1.0.0b251016
agent-framework-mem0                     1.0.0b251016
agent-framework-purview                  1.0.0b251016
agent-framework-redis                    1.0.0b251016

Image

And here is an example I based on the Agent Workflow - Content Review with Quality Routing sample: https://github.com/microsoft/agent-framework/blob/main/python/samples/getting_started/devui/workflow_agents/workflow.py

```python
# Copyright (c) Microsoft. All rights reserved.

"""Agent Workflow - Content Review with Quality Routing.

This sample demonstrates:
- Using agents directly as executors
- Conditional routing based on structured outputs
- Quality-based workflow paths with convergence

Use case: Content creation with automated review.
Writer creates content, Reviewer evaluates quality:
  - High quality (score >= 80): → Publisher → Summarizer
  - Low quality (score < 80): → Editor → Publisher → Summarizer
Both paths converge at Summarizer for final report.
"""

from agent_framework import ConcurrentBuilder
from agent_framework.azure import AzureOpenAIChatClient
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv

load_dotenv("../.env")

# Create Azure OpenAI chat client
CREDENTIAL = DefaultAzureCredential()
chat_client = AzureOpenAIChatClient(credential=CREDENTIAL)

# Create Writer agent - generates content
writer = chat_client.create_agent(
    name="Writer",
    instructions=(
        "You are an excellent content writer. "
        "Create clear, engaging content based on the user's request. "
        "Focus on clarity, accuracy, and proper structure."
    ),
)

tagline_writer = chat_client.create_agent(
    name="Tagline Writer",
    instructions=(
        "You are a creative tagline writer. "
        "Generate catchy and memorable taglines that encapsulate the essence of the content provided."
    ),
)


workflow = (
    ConcurrentBuilder().participants([writer, tagline_writer]).build()
)


def main():
    """Launch the branching workflow in DevUI."""
    import logging

    from agent_framework.devui import serve

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    logger = logging.getLogger(__name__)

    logger.info("Starting Agent Workflow (Content Review with Quality Routing)")
    logger.info("Available at: http://localhost:8093")
    logger.info("\nThis workflow demonstrates:")
    logger.info("- Conditional routing based on structured outputs")
    logger.info("- Path 1 (score >= 80): Reviewer → Publisher → Summarizer")
    logger.info("- Path 2 (score < 80): Reviewer → Editor → Publisher → Summarizer")
    logger.info("- Both paths converge at Summarizer for final report")

    serve(entities=[workflow], port=8093, auto_open=True)


if __name__ == "__main__":
    main()
```

### PR DESCRIPTION
**Pull request by victordibia**
### Motivation and Context 

Resolve timestamp overwriting and Content serialization errors

- Fix tool call timestamps being overwritten on each render (#1483)
- Add recursive Content serialization to handle ChatMessage and nested objects (#1548)
- Implement proper MCP tool cleanup on server shutdown
- Add timestamp field to function_result.complete events
- Enhance credential and client resource cleanup 
- Improve oai responses format support (emit life cycle events for agents and workflows)

Fixes #1483, 
Fixes #1548
Partial improvements for #1476

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/agent-framework/blob/main/CONTRIBUTING.md)
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] **Is this a breaking change?** If yes, add "[BREAKING]" prefix to the title of the PR.

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/agent-framework/blob/af2a51998e6e6e19368b6df5f78b912edd0d0406/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>11681</b></td><td><b>1881</b></td><td><b>83%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1371 | 98 :zzz: | 0 :x: | 0 :fire: | 27.041s :stopwatch: |

File: python/packages/devui/agent_framework_devui/ui/assets/index-D_Y1oSGu.js [hunk 1]
```diff
@@ -0,0 +1,577 @@
...
+ * @license React
+ * react-jsx-runtime.production.js
+ *
+ * Copyright (c) Meta Platforms, Inc. and affiliates.
```
Comment (ekzhu) [inline python/packages/devui/agent_framework_devui/ui/assets/index-D_Y1oSGu.js:5]: Are we okay with shipping this asset with the copyright?

Comment (victordibia) [reply python/packages/devui/agent_framework_devui/ui/assets/index-D_Y1oSGu.js:5]: This is part of the MIT License for React. 
Happy to hear more thoughts
