### PR TITLE
.NET: Fixes AgentWithHostedMCP chat fails: ErrorHTTP 404 (: 404) Resource not found

### LINKED ISSUE #3195: Python: .NET: `AgentWithHostedMCP` chat fails: `ErrorHTTP 404 (: 404) Resource not found`
**Description:**
After deploying [AgentWithHostedMCP](https://github.com/microsoft/agent-framework/tree/main/dotnet/samples/HostedAgents/AgentWithHostedMCP), chatting in the Agent Playground on the Foundry Portal fails with the error:
"ErrorHTTP 404 (: 404) Resource not found."
Image

In addition, running Pytest also fails with the error "ID cannot be null or empty (Parameter 'id')", as shown below:
Image

**Steps to Reproduce:**
1. Initialize the project: `azd init --template Azure-Samples/ai-foundry-starter-basic`.
2. Initialize AI agent: `azd ai agent init -m https://github.com/microsoft/agent-framework/blob/main/dotnet/samples/HostedAgents/AgentWithHostedMCP/agent.yaml` and select location `northcentralus`.
3. Run `azd up`.
4. Navigate to agent playground on the Foundry Portal and enter "How do I create an HTTP-triggered Azure Function in Python?" in the chat.
5. For pytest, copy the folder [tests](https://github.com/coreai-microsoft/foundry-golden-path/tree/main/idea-to-proto/01-build-agent-in-code/tests) to the root directory.
6. Create a new .env file and add the following content.
```
AZURE_AI_PROJECT_ENDPOINT=""https://ai-account-bvmg7v2ge46ec.services.ai.azure.com/api/projects/ai-project-mhweb2""
AGENT_VERSION=1
AGENT_TEST_MESSAGE="How do I create an HTTP-triggered Azure Function in Python?"
AGENT_KIND=hosted
AGENT_NAME="WebSearchAgent"
```
7. Run `cd tests` and `pytest test_agent.py -v -s`.

**Environment:**
- Azd version: azd version 1.23.0-beta.1-daily.5744372 (commit 35c7b9a4a09b4a26b2e99b830746799c49f53fd3).
- AI Agent Extension version: 0.1.5-preview
- Agent: [AgentWithHostedMCP](https://github.com/microsoft/agent-framework/tree/main/dotnet/samples/HostedAgents/AgentWithHostedMCP)
- OS: Windows
- Location: `northcentralus`.

**Expected Behavior:**
Chatting is successful on the agent playground, and pytest also works successfully.

@JeffreyCA and @rajeshkamal5050 for notification.

### PR DESCRIPTION
**Pull request by rogerbarreto**
### Motivation and Context

- Fixes #3195

### CODE REVIEW

File: dotnet/samples/HostedAgents/AgentWithHostedMCP/Program.cs [hunk 1]
```diff
@@ -26,6 +25,7 @@
     new Uri(endpoint),
     new DefaultAzureCredential())
     .GetResponsesClient(deploymentName)
+    .AsIChatClient()
     .CreateAIAgent(
```
Comment (westey-m) [inline dotnet/samples/HostedAgents/AgentWithHostedMCP/Program.cs:32]: Is this sample using some really old packages? We don't have a sync CreateAIAgent anymore after all, especially not on IChatClient.  It should now all be AsAIAgent right?  Also, why would we not use the extension method on the responses client directly.  It should be equivalent to the one on IChatClient, right?

Comment (rogerbarreto) [reply dotnet/samples/HostedAgents/AgentWithHostedMCP/Program.cs:32]: - ❌ Cannot be applied right now — Azure.AI.AgentServer.AgentFramework (even the latest beta.8) depends on the old
  Microsoft.Agents.AI@1.0.0-preview.251125.1, which:
    - Uses CreateAIAgent (not AsAIAgent)
    - Has no AsAIAgent extension on ResponsesClient
    - Uses AgentRunResponse type which was renamed to AgentResponse in newer versions
   - Adding Microsoft.Agents.AI.OpenAI@1.0.0-preview.260212.1 causes a runtime TypeLoadException because of the
  AgentRunResponse → AgentResponse rename in Microsoft.Agents.AI.Abstractions.
