### PR TITLE
.NET: fix: WorkflowAsAgent Sample

### LINKED ISSUE #1613: .NET: Cannot reuse Workflow with shared Executor instances that do not implement IResettableExecutor
- Sample: https://github.com/microsoft/agent-framework/tree/main/dotnet/samples/GettingStarted/Workflows/Agents/WorkflowAsAnAgent
- Detail: Running the sample linked above will result in exception `InvalidOperationException("Cannot reuse Workflow with shared Executor instances that do not implement IResettableExecutor.");` when the conversation exceeds one turn.

### PR DESCRIPTION
**Pull request by lokitoth**
When we started introducing the different execution modes to solidify the concurrency model, we broke the WorkflowAsAgent Sample, which was not updated for either of `IResettableExecutor` or Cross-Run Shareable.

The fix is to make public and switch to using the `ChatForwardingExecutor` in place of a self-defined `ConcurrentStartExecutor`, and make the `ConcurrentAggregationExecutor` implement `IResettableExecutor`

### Description

* Fixes the Workflow in WorkflowAsAgent sample to be ChatProtocol and resettable (closes #1613)
* Also makes ChatForwardingExecutor public

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/agent-framework/blob/main/CONTRIBUTING.md)
- [x] All unit tests pass, and I have added new tests where possible
- [ ] ~~**Is this a breaking change?** If yes, add "[BREAKING]" prefix to the title of the PR.~~

### CODE REVIEW

File: dotnet/samples/GettingStarted/Workflows/Agents/WorkflowAsAnAgent/WorkflowFactory.cs [hunk 1]
```diff
@@ -86,5 +63,12 @@ public override async ValueTask HandleAsync(ChatMessage message, IWorkflowContex
                 await context.YieldOutputAsync(formattedMessages, cancellationToken);
             }
         }
+
+        /// <inheritdoc/>
+        public ValueTask ResetAsync()
+        {
+            this._messages.Clear();
+            return default;
+        }
```
[the remark this answers is not in the document]
Comment (lokitoth) [reply dotnet/samples/GettingStarted/Workflows/Agents/WorkflowAsAnAgent/WorkflowFactory.cs:72]: This line already uses `this.`

File: dotnet/src/Microsoft.Agents.AI.Workflows/ChatForwardingExecutor.cs [hunk 2]
```diff
@@ -4,17 +4,26 @@
 using System.Threading.Tasks;
 using Microsoft.Extensions.AI;
 
-namespace Microsoft.Agents.AI.Workflows.Specialized;
+namespace Microsoft.Agents.AI.Workflows;
 
-/// <summary>Executor that forwards all messages.</summary>
-internal sealed class ChatForwardingExecutor(string id) : Executor(id, declareCrossRunShareable: true), IResettableExecutor
+/// <summary>
+/// A ChatProtocol executor that forwards all messages it receives. Useful for splitting inputs into parallel
```
Comment (stephentoub) [inline dotnet/src/Microsoft.Agents.AI.Workflows/ChatForwardingExecutor.cs:24]: At the moment it's only handling/forwarding string/ChatMessage/`List<ChatMessage>`/TurnToken. Can you remind me why it doesn't work to just have it have a catch-all handler for object?

Comment (lokitoth) [reply dotnet/src/Microsoft.Agents.AI.Workflows/ChatForwardingExecutor.cs:24]: We cannot have a CatchAll handler for `object` because it would leak the `JsonElement` object through the abstraction when resuming from a Checkpoint if it is serialized to JSON. Unfortunately, System.Text.Json is incapable of handling `object` as a target type in an easy manner or one that I expect could work generally without weird edge cases.

We could use `PortableValue`, but we disallow passing forward a `PortableValue` because we would not be able to validate / transform it to a real type to route the message (since checkpoint deletes real type information in favour of TypeId, and using TypeId for inheritance does not always work).

We would have to give up on AOT in order to be able to load types by name to make this work properly, or build a big type table, and still likely run into issues.

Comment (lokitoth) [reply dotnet/src/Microsoft.Agents.AI.Workflows/ChatForwardingExecutor.cs:24]: Expanding on the above a bit: 

We could build `ChatForwardingExecutor` with a catchall on `PortableValue`, check the type, and extract/forward it only when the type matches. But that would mean that any message sent to it will cause the handler to be invoked, even if it could be known a priori that it does not handle that type of message.

I did update it to take the same set of inputs as ChatProtocolExecutor for consistency, though.

The correct long-term fix is not easy, because we need to have definite knowledge of the source runtime `Type` that can survive a serialization/deserialization boundary; AOT makes that difficult because load-type-by-name does not work in that context.

**Comment by lokitoth** [comment]
Added one more fix to update for a change in how message aggregation happens in `AIAgentHostExecutor` post #1439

**Comment by lokitoth** [comment]
Pending #1612
