### PR TITLE
.NET: Adding Image Multi Modality Sample

### LINKED ISSUE #687: .NET: Add Multimodal Input Sample for ChatClients, Agents
Create a sample that covers a multi modal scenario with Images as used in the related issue below:

- #669

```python
import asyncio 
from agent_framework import ChatMessage, DataContent, TextContent, Role
from agent_framework.openai import OpenAIChatClient

# Simple 1x1 test image
TEST_IMAGE_B64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg=="


async def test_multimodal_agent(): 
    # Create agent
    agent = OpenAIChatClient().create_agent(
        name="VisionAgent",
        instructions="You are a helpful assistant that can analyze images.",
    )
    
    # Create a multimodal message with text + image
    multimodal_message = ChatMessage(
        role=Role.USER,
        contents=[
            TextContent(text="What do you see in this image?"),
            DataContent(
                uri=f"data:image/png;base64,{TEST_IMAGE_B64}",
                media_type="image/png"
            )
        ]
    )
    
    try:
        # This should work if multimodal is supported
        result = await agent.run(multimodal_message)
        print("✅ SUCCESS: Agent processed multimodal input!")
        print(f"Response: {result.text}")
        return True
        
    except Exception as e:
        print("❌ FAILED: Agent cannot process multimodal input")
        print(f"Error: {e}")
        return False
 
async def main():  
    await test_multimodal_agent() 


if __name__ == "__main__":
    asyncio.run(main())
```

### PR DESCRIPTION
**Pull request by rogerbarreto**
### Motivation and Context

- Resolves #687

### CODE REVIEW

File: dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    model: deploymentName,
+    name: "VisionAgent",
+    instructions: "You are a helpful agent that can analyze images");
+
+ChatMessage message = new(ChatRole.User, [
+    new TextContent("What do you see in this image?"),
+
+    // A single yellow pixel Base64 encoded PNG image
+    new DataContent("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==", "image/png")
+]);
```
Comment (markwallace-microsoft) [inline dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:23]: Can we add a more interesting image?

This is what we used in SK

```csharp
    public async Task UseOpenAIResponseAgentWithImageContentAsync()
    {
        // Define the agent
        OpenAIResponseAgent agent = new(this.Client)
        {
            Name = "ResponseAgent",
            Instructions = "Provide a detailed description including the weather conditions.",
        };

        ICollection<ChatMessageContent> messages =
        [
            new ChatMessageContent(
                AuthorRole.User,
                items: [
                    new TextContent("What is in this image?"),
                    new ImageContent(new Uri("https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"))
                ]
            ),
        ];

        // Invoke the agent and output the response
        var responseItems = agent.InvokeAsync(messages);
        await foreach (ChatMessageContent responseItem in responseItems)
        {
            WriteAgentChatMessage(responseItem);
        }
    }
```

Comment (rogerbarreto) [reply dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:23]: I made the change and get empty response for different models which leaves me to think that the service doesn't support providing image Uri, only Base64.

I have two options which I tested the first and works.

1. Change the Sample from Azure AI Foundry to Azure OpenAI providing the Uri.
2. Modify the sample to download the image, and sent it over to Azure AI Foundry as a binary content.

Comment (rogerbarreto) [reply dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:23]: As discussed, changing to option 1.

Comment (stephentoub) [reply dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:23]: (You could also have this be multi agent, where the first agent uses IImageGenerator to create an image that's sent to the second agent to analyze.)

File: dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    .CreateAIAgent(
+        name: "VisionAgent",
+        instructions: "You are a helpful agent that can analyze images");
+
+ChatMessage message = new(ChatRole.User, [
+    new TextContent("What do you see in this image?"),
+    new UriContent("https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg", "image/jpeg")
+]);
+
+var thread = agent.GetNewThread();
```
Comment (SergeyMenshykh) [inline dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:25]: The thread is unused.

File: dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+
+var agent = new AzureOpenAIClient(new Uri(endpoint), new AzureCliCredential())
+    .GetChatClient(deploymentName)
+    .CreateAIAgent(
+        name: "VisionAgent",
+        instructions: "You are a helpful agent that can analyze images");
+
+ChatMessage message = new(ChatRole.User, [
+    new TextContent("What do you see in this image?"),
+    new UriContent("https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg", "image/jpeg")
```
Comment (SergeyMenshykh) [inline dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:22]: The sample name implies showing how to use images with agents, but it does not mention the multimodality aspect that the sample actually demonstrates. Consider renaming this sample to reflect the multimodality aspect.

Comment (rogerbarreto) [reply dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:22]: I intentionally called it as UsingImages given the simplicity of it using images with agents.

To call it a multi modal sample I would think that a more complex sample would suit best, adding document, audio and image with agents.

File: dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs (hunk 1 above)
Comment (rogerbarreto) [reply dotnet/samples/GettingStarted/Agents/Agent_Step11_UsingImages/Program.cs:23]: Tracking your suggestion here:

- https://github.com/microsoft/agent-framework/issues/697
