### PR TITLE
.NET: Update to latest Azure.AI.*, OpenAI, and M.E.AI*

### LINKED ISSUE #2869: .NET: MissingMethodException on AIProjectClient.GetAIAgent
Trying to use Agent Framework with the v2 Prompt agent in Microsoft Foundry and receiving "Method not found" Exception. 

**Code**
```c#
var aiProjectClient = new AIProjectClient(new Uri(configuration.AIProjectEndpoint), new AzureCliCredential());
 var existingAgents = aiProjectClient.Agents.GetAgents();
 var existingAgent = existingAgents.FirstOrDefault(q => q.Name == _agentName);
AIAgent agent = aiProjectClient.GetAIAgent(existingAgent);
```
**Exception**
```
System.MissingMethodException: Method not found: 'OpenAI.Responses.OpenAIResponseClient OpenAI.OpenAIClient.GetOpenAIResponseClient(System.String)'.
          at Microsoft.Agents.AI.AzureAI.AzureAIProjectChatClient..ctor(AIProjectClient aiProjectClient, AgentReference agentReference, String defaultModelId, ChatOptions chatOptions)
          at Microsoft.Agents.AI.AzureAI.AzureAIProjectChatClient..ctor(AIProjectClient aiProjectClient, AgentReference agentReference, String defaultModelId, ChatOptions chatOptions)
          at Microsoft.Agents.AI.AzureAI.AzureAIProjectChatClient..ctor(AIProjectClient aiProjectClient, AgentVersion agentVersion, ChatOptions chatOptions)
          at Microsoft.Agents.AI.AzureAI.AzureAIProjectChatClient..ctor(AIProjectClient aiProjectClient, AgentRecord agentRecord, ChatOptions chatOptions)
          at Azure.AI.Projects.AzureAIProjectChatClientExtensions.CreateChatClientAgent(AIProjectClient aiProjectClient, AgentRecord agentRecord, ChatClientAgentOptions agentOptions, Func`2 clientFactory, IServiceProvider services)
          at Azure.AI.Projects.AzureAIProjectChatClientExtensions.CreateChatClientAgent(AIProjectClient AIProjectClient, AgentRecord agentRecord, IList`1 tools, Func`2 clientFactory, Boolean requireInvocableTools, IServiceProvider services)
          at Azure.AI.Projects.AzureAIProjectChatClientExtensions.GetAIAgent(AIProjectClient aiProjectClient, AgentRecord agentRecord, IList`1 tools, Func`2 clientFactory, IServiceProvider services)
```

Tried adding the below nuget Packages in an attempt to find the missing method
- Azure.AI.OpenAI 2.8.0-beta.1
- Azure.AI.Projects 1.2.0-beta.5
- Azure.AI.Projects.OpenAI  1.0.0-beta.5
- Microsoft.Agents.AI 1.0.0-preview.251204.1
- Microsoft.Agents.AI.AzureAI 1.0.0-preview.251204.1
- Microsoft.Agents.AI.OpenAI 1.0.0-preview.251204.1
- Microsoft.Extensions.AI 10.1.1
- Microsoft.Extensions.AI.OpenAI 10.1.1-preview.1.25612.2

### PR DESCRIPTION
**Pull request by stephentoub**
Absorb breaking changes in Responses surface area PR.

- Fixes #2869

### CODE REVIEW

File: dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs [hunk 1]
```diff
@@ -2,7 +2,6 @@
 
 using AgentWebChat.AgentHost.Utilities;
 using Azure;
-using Azure.AI.Inference;
 using Microsoft.Extensions.AI;
```
Comment (stephentoub) [inline dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs:4]:
```suggestion
```

File: dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs [hunk 2]
```diff
@@ -2,8 +2,6 @@
 
 using AgentWebChat.AgentHost.Utilities;
 using Azure;
-using Azure.AI.Inference;
-using Microsoft.Extensions.AI;
 using OllamaSharp;
```
Comment (stephentoub) [inline dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs:5]:
```suggestion
using Microsoft.Extensions.AI;
using OllamaSharp;
```

File: dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs [hunk 3]
```diff
@@ -2,7 +2,6 @@
 
 using AgentWebChat.AgentHost.Utilities;
 using Azure;
```
Comment (stephentoub) [inline dotnet/samples/AgentWebChat/AgentWebChat.AgentHost/Utilities/ChatClientExtensions.cs]:
```suggestion
```

**Comment by stephentoub** [comment]
@rogerbarreto, there are some integration test failures that look like they'll need real fixes. I won't be able to look for awhile, if you have time to take this over. Given the one failure I looked at briefly, I'm concerned it's going to be tricky, but hopefully I'm wrong.

**Comment by rogerbarreto** [comment]
@stephentoub Thanks, I'm currently working on them

All works when changing the `Options.Model = null` for using the `Patch.Remove("$.model"u8)` which marks the json with a `__PLACE_HOLDER__` that the serialization will ignore and not pass-forward.

I'm currently checking that we do have a `GetProjectResponsesClientForAgent(AgentReference)` that would not need to set manually this agent options but it seems to not work with the current endpoint that was working before with `GetProjectResponsesClientF`... going thru this to understand what I'm missing...

**Comment by stephentoub** [comment]
I'm concerned there may be a design problem here.

- OpenAI requires the CreateResponseOptions.Model to be set even if it's provided to the GetResponseClient method. That means a library like the IChatClient implementation needs to look at the default and explicitly set it:
https://github.com/dotnet/extensions/blob/eedc644224ec1e84a52fb303c0e613f059ce5a8d/src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs#L696

- The OpenAI client requires a model to be passed to GetResponsesClient. 

- Foundry requires model to _not_ be set when setting Agent

- Projects removed its Model extension method that used json patch to set $.model

How is a library like AF/IChatClient supposed to use Responses to set Agent and not set Model?

cc: @trrwilson, @joseharriaga, @jeffhandley, @rogerbarreto

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by stephentoub** [comment]
@trrwilson, it also seems wrong to me that the Foundry service errors in this case at all. I argue the service should be more lenient in what it accepts... if you pass both agent and model, it should just ignore the model or use it as an override (same for any other settings baked into the agent). Forcing everyone to understand that relationship doesn't meaningfully help devs as far as I can see, and it's unclear to me what bugs this would actually mitigate... seems like it'll only serve to cause more work for people to try to work around this, causing friction for little-to-no gain.

**Comment by markwallace-microsoft** [comment]
Integration tests are failing. This integration test has issues and needs to be skipped.

```
[xUnit.net 00:00:12.33]     Microsoft.Agents.AI.Workflows.Declarative.IntegrationTests.MediaInputTest.ValidateFileUrlAsync(fileSource: "https://sample-files.com/downloads/images/jpg/web_"···, mediaType: "image/jpeg") [FAIL]
[xUnit.net 00:00:12.33]       Assert.NotEmpty() Failure: Collection was empty
[xUnit.net 00:00:12.33]       Stack Trace:
```
